export const MEALS_DB = [

  {
    idMeal: 'id001',
    strMeal: 'Nasi Goreng Spesial',
    strCategory: 'Nasi & Mie',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&q=80',
    cookTime: '30 menit',
    kalori: '450 kkal',
    porsi: '3-4 orang',
    isFeatured: true,
    strIngredients: [
      { ing: 'Nasi putih (dingin semalam)', msr: '3 piring' },
      { ing: 'Telur ayam', msr: '3 butir' },
      { ing: 'Bawang merah', msr: '6 siung' },
      { ing: 'Bawang putih', msr: '4 siung' },
      { ing: 'Cabai merah keriting', msr: '3 buah' },
      { ing: 'Udang kupas', msr: '100 gram' },
      { ing: 'Kecap manis', msr: '3 sdm' },
      { ing: 'Saus tiram', msr: '1 sdm' },
      { ing: 'Garam', msr: 'secukupnya' },
      { ing: 'Merica bubuk', msr: 'secukupnya' },
      { ing: 'Minyak goreng', msr: '3 sdm' },
      { ing: 'Daun bawang', msr: '2 batang' },
    ],
    strInstructions: [
      'Haluskan bawang merah, bawang putih, dan cabai merah menggunakan blender atau ulekan.',
      'Panaskan minyak di wajan besar. Tumis bumbu halus hingga harum dan matang, sekitar 3 menit.',
      'Masukkan udang, aduk hingga berubah warna. Geser ke pinggir wajan, masukkan telur dan orak-arik.',
      'Masukkan nasi putih, aduk rata dengan bumbu dan telur menggunakan api besar.',
      'Tambahkan kecap manis, saus tiram, garam, dan merica. Aduk terus sekitar 5 menit hingga nasi kering dan berbumbu.',
      'Masukkan daun bawang cincang, aduk sebentar. Angkat dan sajikan dengan acar dan kerupuk.',
    ],
  },
  {
    idMeal: 'id002',
    strMeal: 'Mie Goreng Jawa',
    strCategory: 'Nasi & Mie',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&q=80',
    cookTime: '20 menit',
    kalori: '380 kkal',
    porsi: '2 orang',
    strIngredients: [
      { ing: 'Mie telur', msr: '200 gram' },
      { ing: 'Telur ayam', msr: '2 butir' },
      { ing: 'Bawang merah', msr: '5 siung' },
      { ing: 'Bawang putih', msr: '3 siung' },
      { ing: 'Cabai rawit', msr: '5 buah' },
      { ing: 'Sawi hijau', msr: '100 gram' },
      { ing: 'Kecap manis', msr: '2 sdm' },
      { ing: 'Kecap asin', msr: '1 sdm' },
      { ing: 'Tomat', msr: '1 buah' },
      { ing: 'Garam & merica', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Rebus mie telur hingga al dente, tiriskan dan beri sedikit minyak agar tidak lengket.',
      'Haluskan bawang merah, bawang putih, dan cabai rawit.',
      'Tumis bumbu halus hingga harum. Masukkan tomat cincang, aduk hingga layu.',
      'Masukkan mie, aduk rata. Beri kecap manis, kecap asin, garam, dan merica.',
      'Masukkan sawi hijau, aduk hingga layu. Sisihkan mie ke pinggir, masukkan telur dan orak-arik, campur rata.',
      'Sajikan dengan taburan bawang goreng dan acar timun.',
    ],
  },
  {
    idMeal: 'id003',
    strMeal: 'Nasi Uduk Betawi',
    strCategory: 'Nasi & Mie',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1596797882870-8c33d90a5b3e?w=400&q=80',
    cookTime: '45 menit',
    kalori: '420 kkal',
    porsi: '4 orang',
    strIngredients: [
      { ing: 'Beras', msr: '3 cangkir' },
      { ing: 'Santan kental', msr: '400 ml' },
      { ing: 'Air', msr: '200 ml' },
      { ing: 'Serai', msr: '2 batang' },
      { ing: 'Daun salam', msr: '3 lembar' },
      { ing: 'Daun pandan', msr: '2 lembar' },
      { ing: 'Garam', msr: '1,5 sdt' },
    ],
    strInstructions: [
      'Cuci beras hingga bersih, rendam 30 menit lalu tiriskan.',
      'Campurkan santan dan air, masak hingga mendidih bersama serai, daun salam, dan pandan.',
      'Masukkan beras ke dalam rice cooker, tuang santan berbumbu, tambahkan garam.',
      'Masak hingga nasi matang. Aduk rata agar santan meresap sempurna.',
      'Sajikan dengan empal, tempe orek, bihun goreng, dan sambal kacang.',
    ],
  },
  {
    idMeal: 'id004',
    strMeal: 'Bubur Ayam Jakarta',
    strCategory: 'Nasi & Mie',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=400&q=80',
    cookTime: '60 menit',
    kalori: '320 kkal',
    porsi: '4 orang',
    strIngredients: [
      { ing: 'Beras', msr: '200 gram' },
      { ing: 'Dada ayam', msr: '300 gram' },
      { ing: 'Kaldu ayam', msr: '1,5 liter' },
      { ing: 'Jahe', msr: '2 cm' },
      { ing: 'Serai', msr: '1 batang' },
      { ing: 'Bawang putih', msr: '4 siung' },
      { ing: 'Garam & merica', msr: 'secukupnya' },
      { ing: 'Kecap asin', msr: '1 sdm' },
    ],
    strInstructions: [
      'Rebus ayam dengan kaldu, jahe, serai, dan bawang putih hingga matang. Suwir ayam, simpan kaldunya.',
      'Masak beras dengan kaldu ayam yang sudah disaring menggunakan api kecil, aduk sesekali.',
      'Masak hingga beras menjadi bubur kental, sekitar 45 menit. Tambahkan garam dan merica.',
      'Sajikan bubur dengan ayam suwir, cakwe, kacang goreng, kerupuk, dan taburan daun bawang.',
    ],
  },
  {
    idMeal: 'id005',
    strMeal: 'Nasi Kuning Tumpeng',
    strCategory: 'Nasi & Mie',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=400&q=80',
    cookTime: '50 menit',
    kalori: '400 kkal',
    porsi: '6 orang',
    strIngredients: [
      { ing: 'Beras', msr: '4 cangkir' },
      { ing: 'Santan', msr: '500 ml' },
      { ing: 'Kunyit bubuk', msr: '2 sdt' },
      { ing: 'Serai', msr: '2 batang' },
      { ing: 'Daun salam', msr: '3 lembar' },
      { ing: 'Daun jeruk', msr: '4 lembar' },
      { ing: 'Garam', msr: '2 sdt' },
    ],
    strInstructions: [
      'Larutkan kunyit bubuk dalam sedikit air hangat.',
      'Masak santan bersama serai, daun salam, daun jeruk, kunyit, dan garam hingga mendidih.',
      'Masukkan beras, masak sambil diaduk hingga santan terserap.',
      'Kukus nasi selama 30 menit hingga matang dan pulen. Cetak dalam cetakan tumpeng.',
      'Sajikan dengan berbagai lauk pelengkap seperti ayam goreng, tempe, telur balado.',
    ],
  },

  {
    idMeal: 'id006',
    strMeal: 'Rendang Daging Sapi',
    strCategory: 'Rendang',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=400&q=80',
    cookTime: '3-4 jam',
    kalori: '520 kkal',
    porsi: '6 orang',
    isFeatured: true,
    strIngredients: [
      { ing: 'Daging sapi (sandung lamur)', msr: '1 kg' },
      { ing: 'Santan kental', msr: '800 ml' },
      { ing: 'Cabai merah kering', msr: '15 buah' },
      { ing: 'Bawang merah', msr: '10 siung' },
      { ing: 'Bawang putih', msr: '6 siung' },
      { ing: 'Jahe', msr: '3 cm' },
      { ing: 'Lengkuas', msr: '4 cm' },
      { ing: 'Kunyit', msr: '2 cm' },
      { ing: 'Serai', msr: '3 batang' },
      { ing: 'Daun jeruk', msr: '8 lembar' },
      { ing: 'Daun kunyit', msr: '2 lembar' },
      { ing: 'Garam', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Haluskan cabai merah, bawang merah, bawang putih, jahe, lengkuas, dan kunyit.',
      'Masak daging bersama bumbu halus, santan, serai geprek, daun jeruk, dan daun kunyit.',
      'Masak dengan api sedang sambil terus diaduk agar tidak hangus. Masak hingga santan mendidih.',
      'Kecilkan api, terus masak dan aduk sesekali hingga santan mengering dan berminyak, sekitar 2-3 jam.',
      'Terus masak hingga daging berwarna coklat gelap dan bumbu kering menempel sempurna.',
      'Angkat jika daging sudah empuk dan berwarna coklat kehitaman. Sajikan dengan nasi panas.',
    ],
  },
  {
    idMeal: 'id007',
    strMeal: 'Rendang Ayam Padang',
    strCategory: 'Rendang',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    cookTime: '90 menit',
    kalori: '460 kkal',
    porsi: '4 orang',
    strIngredients: [
      { ing: 'Ayam potong', msr: '1 ekor' },
      { ing: 'Santan kental', msr: '600 ml' },
      { ing: 'Cabai merah', msr: '10 buah' },
      { ing: 'Bawang merah', msr: '8 siung' },
      { ing: 'Bawang putih', msr: '5 siung' },
      { ing: 'Lengkuas', msr: '3 cm' },
      { ing: 'Kunyit', msr: '2 cm' },
      { ing: 'Serai', msr: '2 batang' },
      { ing: 'Daun jeruk', msr: '6 lembar' },
      { ing: 'Garam', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Haluskan semua bumbu: cabai, bawang merah, bawang putih, lengkuas, dan kunyit.',
      'Tumis bumbu halus hingga harum, masukkan serai geprek dan daun jeruk.',
      'Masukkan potongan ayam, aduk hingga berubah warna dan bumbu meresap.',
      'Tuang santan, masak dengan api sedang sambil sesekali diaduk hingga santan mengering.',
      'Masak terus hingga ayam empuk dan bumbu menempel berwarna kecoklatan.',
    ],
  },

  {
    idMeal: 'id008',
    strMeal: 'Ayam Bakar Kecap',
    strCategory: 'Ayam',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400&q=80',
    cookTime: '60 menit',
    kalori: '380 kkal',
    porsi: '4 orang',
    strIngredients: [
      { ing: 'Ayam utuh potong 8', msr: '1 ekor' },
      { ing: 'Kecap manis', msr: '5 sdm' },
      { ing: 'Bawang merah', msr: '6 siung' },
      { ing: 'Bawang putih', msr: '4 siung' },
      { ing: 'Jahe', msr: '2 cm' },
      { ing: 'Kemiri', msr: '4 butir' },
      { ing: 'Ketumbar', msr: '1 sdt' },
      { ing: 'Kunyit', msr: '1 cm' },
      { ing: 'Minyak goreng', msr: '3 sdm' },
      { ing: 'Garam', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Haluskan bawang merah, bawang putih, jahe, kemiri, ketumbar, dan kunyit.',
      'Tumis bumbu halus hingga harum dan matang. Masukkan ayam, aduk rata.',
      'Tambahkan kecap manis, garam, dan sedikit air. Masak hingga bumbu meresap dan ayam setengah matang.',
      'Angkat ayam, bakar di atas bara api atau panggangan sambil dioles sisa bumbu kecap.',
      'Bakar hingga kecoklatan dan harum. Sajikan dengan lalapan dan sambal.',
    ],
  },
  {
    idMeal: 'id009',
    strMeal: 'Ayam Goreng Kalasan',
    strCategory: 'Ayam',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400&q=80',
    cookTime: '90 menit',
    kalori: '420 kkal',
    porsi: '4 orang',
    strIngredients: [
      { ing: 'Ayam potong', msr: '1 ekor' },
      { ing: 'Air kelapa muda', msr: '500 ml' },
      { ing: 'Bawang merah', msr: '8 siung' },
      { ing: 'Bawang putih', msr: '5 siung' },
      { ing: 'Kemiri', msr: '5 butir' },
      { ing: 'Ketumbar', msr: '2 sdt' },
      { ing: 'Kunyit', msr: '2 cm' },
      { ing: 'Lengkuas', msr: '2 cm' },
      { ing: 'Garam', msr: '1,5 sdt' },
      { ing: 'Minyak untuk menggoreng', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Haluskan bawang merah, bawang putih, kemiri, ketumbar, kunyit, dan lengkuas.',
      'Rebus ayam dengan bumbu halus, air kelapa, dan garam hingga matang dan air menyusut.',
      'Diamkan ayam dalam bumbu minimal 30 menit agar meresap sempurna.',
      'Goreng ayam dalam minyak panas hingga kuning keemasan dan renyah.',
      'Sajikan dengan nasi hangat, lalapan, dan sambal terasi.',
    ],
  },
  {
    idMeal: 'id010',
    strMeal: 'Opor Ayam',
    strCategory: 'Ayam',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    cookTime: '60 menit',
    kalori: '480 kkal',
    porsi: '6 orang',
    strIngredients: [
      { ing: 'Ayam potong', msr: '1 ekor' },
      { ing: 'Santan kental', msr: '400 ml' },
      { ing: 'Santan encer', msr: '300 ml' },
      { ing: 'Bawang merah', msr: '8 siung' },
      { ing: 'Bawang putih', msr: '5 siung' },
      { ing: 'Kemiri', msr: '5 butir' },
      { ing: 'Ketumbar', msr: '2 sdt' },
      { ing: 'Merica', msr: '1 sdt' },
      { ing: 'Serai', msr: '2 batang' },
      { ing: 'Daun salam', msr: '3 lembar' },
      { ing: 'Lengkuas', msr: '3 cm' },
      { ing: 'Garam', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Haluskan bawang merah, bawang putih, kemiri, ketumbar, dan merica.',
      'Tumis bumbu halus bersama serai geprek, daun salam, dan lengkuas hingga harum.',
      'Masukkan ayam, aduk rata hingga berubah warna.',
      'Tuang santan encer, masak hingga mendidih. Tambahkan santan kental.',
      'Masak dengan api kecil sambil sesekali diaduk agar santan tidak pecah.',
      'Masak hingga ayam empuk dan kuah mengental kekuningan. Koreksi rasa.',
    ],
  },
  {
    idMeal: 'id011',
    strMeal: 'Ayam Geprek Sambal Bawang',
    strCategory: 'Ayam',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&q=80',
    cookTime: '40 menit',
    kalori: '510 kkal',
    porsi: '2 orang',
    strIngredients: [
      { ing: 'Dada ayam', msr: '2 buah' },
      { ing: 'Tepung terigu', msr: '150 gram' },
      { ing: 'Tepung tapioka', msr: '50 gram' },
      { ing: 'Telur', msr: '1 butir' },
      { ing: 'Bawang putih bubuk', msr: '1 sdt' },
      { ing: 'Garam & merica', msr: 'secukupnya' },
      { ing: 'Cabai rawit', msr: '10 buah' },
      { ing: 'Bawang putih (sambal)', msr: '6 siung' },
      { ing: 'Minyak goreng', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Pipihkan dada ayam dengan palu daging. Marinasi dengan garam, merica, dan bawang putih bubuk.',
      'Balur ayam dengan campuran tepung terigu, tapioka, dan telur. Pastikan merata.',
      'Goreng ayam dalam minyak panas hingga kuning keemasan dan matang.',
      'Buat sambal: goreng cabai rawit dan bawang putih, haluskan kasar dengan garam.',
      'Geprek ayam goreng, tuang sambal di atasnya. Sajikan dengan nasi dan lalapan.',
    ],
  },

  {
    idMeal: 'id012',
    strMeal: 'Soto Ayam Lamongan',
    strCategory: 'Soto & Sup',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80',
    cookTime: '75 menit',
    kalori: '350 kkal',
    porsi: '6 orang',
    isFeatured: true,
    strIngredients: [
      { ing: 'Ayam kampung', msr: '1 ekor' },
      { ing: 'Air', msr: '2 liter' },
      { ing: 'Bawang merah', msr: '8 siung' },
      { ing: 'Bawang putih', msr: '5 siung' },
      { ing: 'Kemiri', msr: '5 butir' },
      { ing: 'Kunyit', msr: '3 cm' },
      { ing: 'Jahe', msr: '2 cm' },
      { ing: 'Serai', msr: '2 batang' },
      { ing: 'Daun salam', msr: '3 lembar' },
      { ing: 'Daun jeruk', msr: '5 lembar' },
      { ing: 'Garam & merica', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Rebus ayam dengan air bersama serai, daun salam, dan daun jeruk hingga matang.',
      'Angkat ayam, suwir dagingnya. Saring kaldu dan kembalikan ke panci.',
      'Haluskan bawang merah, bawang putih, kemiri, kunyit, dan jahe. Goreng bumbu hingga harum.',
      'Masukkan bumbu goreng ke dalam kaldu, didihkan. Tambahkan garam dan merica.',
      'Sajikan dengan bihun, ayam suwir, telur rebus, tauge, daun seledri, bawang goreng, dan koya.',
    ],
  },
  {
    idMeal: 'id013',
    strMeal: 'Rawon Surabaya',
    strCategory: 'Soto & Sup',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&q=80',
    cookTime: '90 menit',
    kalori: '420 kkal',
    porsi: '6 orang',
    strIngredients: [
      { ing: 'Daging sapi', msr: '500 gram' },
      { ing: 'Kluwek', msr: '5 buah' },
      { ing: 'Bawang merah', msr: '8 siung' },
      { ing: 'Bawang putih', msr: '5 siung' },
      { ing: 'Kemiri', msr: '4 butir' },
      { ing: 'Kunyit', msr: '2 cm' },
      { ing: 'Lengkuas', msr: '3 cm' },
      { ing: 'Serai', msr: '2 batang' },
      { ing: 'Daun jeruk', msr: '6 lembar' },
      { ing: 'Air', msr: '1,5 liter' },
      { ing: 'Garam & gula', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Belah kluwek, ambil isinya dan haluskan bersama bawang merah, bawang putih, kemiri, dan kunyit.',
      'Rebus daging sapi hingga empuk, potong sesuai selera.',
      'Tumis bumbu halus hingga harum. Masukkan lengkuas geprek, serai, dan daun jeruk.',
      'Masukkan bumbu ke dalam kaldu daging. Tambahkan garam dan gula.',
      'Masak hingga kuah berwarna hitam pekat dari kluwek. Koreksi rasa.',
      'Sajikan dengan tauge, telur asin, sambal, dan kerupuk udang.',
    ],
  },
  {
    idMeal: 'id014',
    strMeal: 'Soto Betawi Santan',
    strCategory: 'Soto & Sup',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=400&q=80',
    cookTime: '90 menit',
    kalori: '480 kkal',
    porsi: '5 orang',
    strIngredients: [
      { ing: 'Daging sapi', msr: '400 gram' },
      { ing: 'Jeroan (babat/paru)', msr: '200 gram' },
      { ing: 'Santan kental', msr: '400 ml' },
      { ing: 'Susu cair', msr: '200 ml' },
      { ing: 'Bawang merah', msr: '10 siung' },
      { ing: 'Bawang putih', msr: '6 siung' },
      { ing: 'Kemiri', msr: '6 butir' },
      { ing: 'Serai', msr: '2 batang' },
      { ing: 'Daun jeruk', msr: '6 lembar' },
      { ing: 'Garam', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Rebus daging dan jeroan terpisah hingga empuk. Potong-potong, sisihkan kaldunya.',
      'Haluskan bawang merah, bawang putih, dan kemiri. Tumis hingga harum.',
      'Masukkan bumbu tumis ke dalam kaldu bersama serai dan daun jeruk.',
      'Tuang santan dan susu cair, masak dengan api kecil agar tidak pecah.',
      'Masukkan daging dan jeroan, masak hingga bumbu meresap. Koreksi rasa.',
      'Sajikan dengan kentang goreng, tomat, daun bawang, emping, dan sambal.',
    ],
  },

  {
    idMeal: 'id015',
    strMeal: 'Ikan Bakar Bumbu Rujak',
    strCategory: 'Seafood',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1576402187878-974f70c890a5?w=400&q=80',
    cookTime: '45 menit',
    kalori: '280 kkal',
    porsi: '4 orang',
    strIngredients: [
      { ing: 'Ikan kakap merah', msr: '1 ekor (800g)' },
      { ing: 'Cabai merah', msr: '6 buah' },
      { ing: 'Bawang merah', msr: '6 siung' },
      { ing: 'Bawang putih', msr: '4 siung' },
      { ing: 'Tomat', msr: '2 buah' },
      { ing: 'Kencur', msr: '1 cm' },
      { ing: 'Terasi', msr: '1 sdt' },
      { ing: 'Gula merah', msr: '1 sdm' },
      { ing: 'Garam', msr: 'secukupnya' },
      { ing: 'Jeruk nipis', msr: '2 buah' },
    ],
    strInstructions: [
      'Bersihkan ikan, lumuri dengan air jeruk nipis dan garam. Diamkan 15 menit.',
      'Haluskan cabai, bawang merah, bawang putih, tomat, kencur, terasi, gula merah, dan garam.',
      'Lumuri ikan dengan bumbu halus hingga merata ke seluruh permukaan dan perut ikan.',
      'Bakar ikan di atas bara api atau panggangan sambil dibalik dan diolesi sisa bumbu.',
      'Bakar hingga matang dan sedikit gosong di beberapa bagian. Sajikan dengan lalapan dan nasi.',
    ],
  },
  {
    idMeal: 'id016',
    strMeal: 'Udang Saus Padang',
    strCategory: 'Seafood',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1559620192-032c4bc4674e?w=400&q=80',
    cookTime: '30 menit',
    kalori: '310 kkal',
    porsi: '3 orang',
    strIngredients: [
      { ing: 'Udang besar', msr: '500 gram' },
      { ing: 'Saus tomat', msr: '4 sdm' },
      { ing: 'Saus sambal', msr: '3 sdm' },
      { ing: 'Bawang merah', msr: '5 siung' },
      { ing: 'Bawang putih', msr: '4 siung' },
      { ing: 'Cabai merah', msr: '4 buah' },
      { ing: 'Cabai rawit', msr: '5 buah' },
      { ing: 'Tomat', msr: '1 buah' },
      { ing: 'Gula & garam', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Bersihkan udang, belah punggungnya tapi jangan sampai putus.',
      'Iris bawang merah, bawang putih, cabai merah, dan cabai rawit.',
      'Tumis bumbu iris hingga harum. Masukkan tomat, aduk hingga layu.',
      'Masukkan saus tomat dan saus sambal, aduk rata. Tambahkan sedikit air.',
      'Masukkan udang, masak hingga udang matang dan saus mengental. Koreksi rasa.',
    ],
  },
  {
    idMeal: 'id017',
    strMeal: 'Pempek Palembang',
    strCategory: 'Seafood',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=400&q=80',
    cookTime: '90 menit',
    kalori: '350 kkal',
    porsi: '4 orang',
    isFeatured: true,
    strIngredients: [
      { ing: 'Ikan tenggiri giling', msr: '500 gram' },
      { ing: 'Tepung tapioka', msr: '250 gram' },
      { ing: 'Air dingin', msr: '100 ml' },
      { ing: 'Garam', msr: '1 sdt' },
      { ing: 'Telur (untuk pempek kapal selam)', msr: '4 butir' },
      { ing: 'Cuka', msr: '100 ml' },
      { ing: 'Gula merah', msr: '100 gram' },
      { ing: 'Cabai rawit', msr: '10 buah' },
      { ing: 'Bawang putih', msr: '3 siung' },
    ],
    strInstructions: [
      'Campur ikan giling dengan garam dan air dingin, aduk rata.',
      'Masukkan tepung tapioka sedikit demi sedikit, uleni hingga kalis.',
      'Bentuk adonan: untuk kapal selam, beri isian telur mentah lalu rekatkan.',
      'Rebus pempek hingga mengapung dan matang. Angkat dan tiriskan.',
      'Buat cuko: rebus cuka, gula merah, cabai, dan bawang putih hingga mengental.',
      'Goreng pempek hingga kecoklatan. Sajikan dengan cuko dan timun.',
    ],
  },

  {
    idMeal: 'id018',
    strMeal: 'Tempe Mendoan',
    strCategory: 'Gorengan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1591111937359-34f627ee38ee?w=400&q=80',
    cookTime: '20 menit',
    kalori: '220 kkal',
    porsi: '4 orang',
    strIngredients: [
      { ing: 'Tempe', msr: '300 gram' },
      { ing: 'Tepung terigu', msr: '150 gram' },
      { ing: 'Tepung beras', msr: '50 gram' },
      { ing: 'Daun bawang', msr: '3 batang' },
      { ing: 'Bawang putih', msr: '3 siung' },
      { ing: 'Ketumbar bubuk', msr: '1 sdt' },
      { ing: 'Kunyit bubuk', msr: '0,5 sdt' },
      { ing: 'Garam', msr: '1 sdt' },
      { ing: 'Air', msr: '200 ml' },
    ],
    strInstructions: [
      'Iris tipis tempe secara diagonal, sekitar 3-4mm agar renyah setelah digoreng.',
      'Haluskan bawang putih, campur dengan tepung terigu, tepung beras, ketumbar, kunyit, dan garam.',
      'Tambahkan air sedikit demi sedikit sambil diaduk hingga adonan cair tapi tidak terlalu encer.',
      'Masukkan irisan daun bawang ke dalam adonan tepung.',
      'Celupkan tempe ke adonan, goreng dalam minyak panas api sedang hingga kuning keemasan.',
      'Sajikan hangat dengan sambal kecap atau cabai rawit.',
    ],
  },
  {
    idMeal: 'id019',
    strMeal: 'Tahu Isi Sayuran',
    strCategory: 'Gorengan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?w=400&q=80',
    cookTime: '30 menit',
    kalori: '180 kkal',
    porsi: '4 orang',
    strIngredients: [
      { ing: 'Tahu putih', msr: '10 buah' },
      { ing: 'Wortel', msr: '1 buah' },
      { ing: 'Kol', msr: '100 gram' },
      { ing: 'Tauge', msr: '50 gram' },
      { ing: 'Daun bawang', msr: '2 batang' },
      { ing: 'Bawang merah', msr: '4 siung' },
      { ing: 'Bawang putih', msr: '3 siung' },
      { ing: 'Tepung terigu', msr: '100 gram' },
      { ing: 'Garam & merica', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Goreng tahu setengah matang, belah dan keluarkan sebagian isinya. Hancurkan isi tahu.',
      'Tumis bawang merah dan bawang putih hingga harum. Masukkan wortel serut, kol, dan tauge.',
      'Aduk rata, tambahkan garam dan merica. Masak hingga sayuran layu.',
      'Masukkan isi tahu hancur, aduk rata. Masukkan daun bawang.',
      'Isi tahu dengan tumisan sayuran. Rekatkan dengan tusuk gigi.',
      'Celup ke adonan tepung encer berbumbu, goreng hingga kuning keemasan.',
    ],
  },
  {
    idMeal: 'id020',
    strMeal: 'Bakwan Jagung',
    strCategory: 'Gorengan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1625944230945-1b7dd3b949ab?w=400&q=80',
    cookTime: '25 menit',
    kalori: '200 kkal',
    porsi: '4 orang',
    strIngredients: [
      { ing: 'Jagung manis', msr: '2 buah' },
      { ing: 'Tepung terigu', msr: '150 gram' },
      { ing: 'Telur', msr: '1 butir' },
      { ing: 'Daun bawang', msr: '3 batang' },
      { ing: 'Bawang putih', msr: '3 siung' },
      { ing: 'Cabai rawit (opsional)', msr: '3 buah' },
      { ing: 'Garam & merica', msr: 'secukupnya' },
      { ing: 'Air', msr: '100 ml' },
    ],
    strInstructions: [
      'Serut jagung dari bonggolnya. Sisihkan.',
      'Haluskan bawang putih. Iris daun bawang dan cabai rawit.',
      'Campurkan tepung terigu, telur, bawang putih halus, garam, merica, dan air. Aduk rata.',
      'Masukkan jagung serut, daun bawang, dan cabai. Aduk rata hingga adonan kental.',
      'Sendokkan adonan ke dalam minyak panas, goreng hingga kuning keemasan di kedua sisi.',
      'Sajikan hangat dengan saus sambal atau cabai rawit.',
    ],
  },
  {
    idMeal: 'id021',
    strMeal: 'Martabak Telur',
    strCategory: 'Gorengan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&q=80',
    cookTime: '40 menit',
    kalori: '450 kkal',
    porsi: '4 orang',
    strIngredients: [
      { ing: 'Kulit lumpia atau kulit martabak', msr: '8 lembar' },
      { ing: 'Daging sapi cincang', msr: '200 gram' },
      { ing: 'Telur ayam', msr: '4 butir' },
      { ing: 'Daun bawang', msr: '4 batang' },
      { ing: 'Bawang merah', msr: '5 siung' },
      { ing: 'Bawang putih', msr: '3 siung' },
      { ing: 'Kari bubuk', msr: '1 sdt' },
      { ing: 'Garam & merica', msr: 'secukupnya' },
    ],
    strInstructions: [
      'Tumis bawang merah, bawang putih, dan daging cincang hingga matang. Beri kari, garam, merica.',
      'Kocok telur, campurkan dengan tumisan daging dan daun bawang iris.',
      'Bentangkan kulit martabak, isi dengan campuran telur-daging.',
      'Lipat kulit martabak membentuk persegi, rekatkan dengan putih telur.',
      'Goreng dalam minyak panas dengan api sedang hingga kecoklatan di semua sisi.',
      'Sajikan dengan acar bawang dan cabai.',
    ],
  },

  {
    idMeal: 'id022',
    strMeal: 'Klepon Pandan',
    strCategory: 'Kue & Jajan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&q=80',
    cookTime: '30 menit',
    kalori: '180 kkal',
    porsi: '20 buah',
    strIngredients: [
      { ing: 'Tepung ketan', msr: '250 gram' },
      { ing: 'Pasta pandan', msr: '1,5 sdt' },
      { ing: 'Air matang', msr: '150 ml' },
      { ing: 'Gula merah', msr: '100 gram' },
      { ing: 'Kelapa parut kasar', msr: '150 gram' },
      { ing: 'Garam', msr: '0,5 sdt' },
    ],
    strInstructions: [
      'Serut gula merah halus untuk isian. Campurkan kelapa parut dengan sedikit garam, kukus 10 menit.',
      'Campur tepung ketan dengan pasta pandan dan garam. Tambahkan air sedikit demi sedikit.',
      'Uleni hingga adonan kalis dan bisa dibentuk. Ambil satu sendok, pipihkan, beri isian gula merah.',
      'Bulatkan adonan hingga gula tertutup sempurna agar tidak bocor saat direbus.',
      'Rebus klepon dalam air mendidih. Angkat saat klepon mengapung ke permukaan.',
      'Gulingkan klepon panas di atas kelapa parut kukus. Sajikan segera.',
    ],
  },
  {
    idMeal: 'id023',
    strMeal: 'Dadar Gulung Isi Kelapa',
    strCategory: 'Kue & Jajan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1596797882870-8c33d90a5b3e?w=400&q=80',
    cookTime: '45 menit',
    kalori: '200 kkal',
    porsi: '15 buah',
    strIngredients: [
      { ing: 'Tepung terigu', msr: '200 gram' },
      { ing: 'Telur', msr: '2 butir' },
      { ing: 'Santan', msr: '400 ml' },
      { ing: 'Pasta pandan', msr: '1 sdt' },
      { ing: 'Garam', msr: '0,5 sdt' },
      { ing: 'Kelapa parut', msr: '200 gram' },
      { ing: 'Gula merah', msr: '150 gram' },
      { ing: 'Daun pandan', msr: '2 lembar' },
    ],
    strInstructions: [
      'Buat isian: masak kelapa parut, gula merah serut, dan daun pandan hingga kering dan wangi.',
      'Buat adonan kulit: campur tepung, telur, santan, pasta pandan, dan garam. Saring.',
      'Panaskan teflon tipis, olesi sedikit minyak. Tuang adonan tipis, buat crepe dadar.',
      'Masak kulit dadar hingga kering dan tidak lengket, sekitar 2 menit.',
      'Letakkan isian kelapa di salah satu sisi kulit dadar. Lipat dan gulung rapi.',
      'Sajikan dadar gulung sebagai camilan atau dessert.',
    ],
  },
  {
    idMeal: 'id024',
    strMeal: 'Onde-Onde Wijen',
    strCategory: 'Kue & Jajan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=400&q=80',
    cookTime: '50 menit',
    kalori: '220 kkal',
    porsi: '20 buah',
    strIngredients: [
      { ing: 'Tepung ketan', msr: '250 gram' },
      { ing: 'Air panas', msr: '150 ml' },
      { ing: 'Gula pasir', msr: '50 gram' },
      { ing: 'Kacang hijau kupas', msr: '200 gram' },
      { ing: 'Gula merah', msr: '100 gram' },
      { ing: 'Santan', msr: '100 ml' },
      { ing: 'Wijen putih', msr: '100 gram' },
    ],
    strInstructions: [
      'Buat isian: rebus kacang hijau hingga lunak, haluskan. Masak dengan gula merah dan santan hingga kering.',
      'Aduk tepung ketan dengan gula pasir dan garam. Tuang air panas sedikit demi sedikit, uleni hingga kalis.',
      'Ambil adonan secukupnya, pipihkan. Isi dengan pasta kacang hijau, bulatkan.',
      'Gulingkan bola onde-onde di atas wijen, tekan lembut agar wijen menempel.',
      'Goreng dalam minyak panas api sedang dengan cara diputar-putar agar matang merata.',
      'Angkat saat wijen keemasan dan onde-onde menggelembung. Tiriskan.',
    ],
  },
  {
    idMeal: 'id025',
    strMeal: 'Lupis Ketan Gula Merah',
    strCategory: 'Kue & Jajan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1542691457-cbe4df041eb2?w=400&q=80',
    cookTime: '90 menit',
    kalori: '250 kkal',
    porsi: '10 buah',
    strIngredients: [
      { ing: 'Beras ketan putih', msr: '500 gram' },
      { ing: 'Santan', msr: '300 ml' },
      { ing: 'Garam', msr: '1 sdt' },
      { ing: 'Daun pisang untuk membungkus', msr: 'secukupnya' },
      { ing: 'Gula merah', msr: '200 gram' },
      { ing: 'Kelapa parut kukus', msr: '150 gram' },
    ],
    strInstructions: [
      'Cuci beras ketan, rendam semalaman. Tiriskan.',
      'Masak santan dengan garam hingga mendidih. Masukkan ketan, aduk rata, masak setengah matang.',
      'Ambil ketan secukupnya, bungkus dengan daun pisang berbentuk silinder, ikat kencang.',
      'Kukus bungkusan ketan selama 60 menit hingga benar-benar matang dan padat.',
      'Buat saus gula merah: larutkan gula merah dengan sedikit air, saring, masak hingga mengental.',
      'Sajikan lupis dipotong-potong dengan saus gula merah dan taburan kelapa parut.',
    ],
  },
  {
    idMeal: 'id026',
    strMeal: 'Cenil Pelangi',
    strCategory: 'Kue & Jajan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1562802378-063ec186a863?w=400&q=80',
    cookTime: '30 menit',
    kalori: '160 kkal',
    porsi: '6 porsi',
    strIngredients: [
      { ing: 'Tepung kanji (tapioka)', msr: '250 gram' },
      { ing: 'Air mendidih', msr: '200 ml' },
      { ing: 'Pasta pandan (hijau)', msr: '1 sdt' },
      { ing: 'Pewarna merah', msr: 'secukupnya' },
      { ing: 'Garam', msr: '0,5 sdt' },
      { ing: 'Kelapa parut', msr: '150 gram' },
      { ing: 'Gula merah cair', msr: '5 sdm' },
    ],
    strInstructions: [
      'Bagi tepung kanji menjadi 3 bagian. Beri warna berbeda (hijau pandan, merah, putih polos).',
      'Siram masing-masing dengan air mendidih dan sedikit garam, aduk hingga adonan kalis.',
      'Bentuk adonan memanjang seperti silinder kecil atau dengan cetakan.',
      'Rebus cenil dalam air mendidih hingga mengapung dan bening. Tiriskan.',
      'Campurkan kelapa parut dengan sedikit garam, kukus 5 menit.',
      'Gulingkan cenil di atas kelapa parut, siram gula merah cair saat menyajikan.',
    ],
  },
  {
    idMeal: 'id027',
    strMeal: 'Kue Putu Bambu',
    strCategory: 'Kue & Jajan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80',
    cookTime: '20 menit',
    kalori: '150 kkal',
    porsi: '10 buah',
    strIngredients: [
      { ing: 'Tepung beras', msr: '200 gram' },
      { ing: 'Pasta pandan', msr: '1 sdt' },
      { ing: 'Air', msr: '100 ml' },
      { ing: 'Garam', msr: '0,5 sdt' },
      { ing: 'Gula merah', msr: '100 gram' },
      { ing: 'Kelapa parut kukus', msr: '100 gram' },
    ],
    strInstructions: [
      'Campur tepung beras, pasta pandan, garam, dan air sedikit demi sedikit hingga tekstur seperti pasir basah.',
      'Serut halus gula merah untuk isian.',
      'Masukkan adonan tepung ke dalam cetakan bambu/aluminium hingga setengah penuh.',
      'Beri isian gula merah serut di tengah, tutup lagi dengan adonan tepung.',
      'Kukus dengan uap panas (taruh di atas panci berisi air mendidih) selama 10-12 menit.',
      'Keluarkan kue putu, sajikan di atas kelapa parut kukus. Nikmati selagi hangat.',
    ],
  },
  {
    idMeal: 'id028',
    strMeal: 'Kue Lapis Pelangi',
    strCategory: 'Kue & Jajan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&q=80',
    cookTime: '90 menit',
    kalori: '230 kkal',
    porsi: '16 potong',
    strIngredients: [
      { ing: 'Tepung beras', msr: '300 gram' },
      { ing: 'Tepung tapioka', msr: '100 gram' },
      { ing: 'Santan kental', msr: '600 ml' },
      { ing: 'Gula pasir', msr: '200 gram' },
      { ing: 'Pasta pandan', msr: '1 sdt' },
      { ing: 'Pewarna merah muda', msr: 'secukupnya' },
      { ing: 'Garam', msr: '0,5 sdt' },
    ],
    strInstructions: [
      'Campur tepung beras, tapioka, santan, gula, dan garam. Aduk rata hingga tidak bergerindil.',
      'Bagi adonan menjadi 3 bagian. Beri warna: hijau pandan, merah muda, dan putih.',
      'Panaskan loyang yang sudah diolesi minyak. Tuang lapis pertama (hijau), kukus 5 menit.',
      'Tuang lapis kedua (putih) di atas lapisan pertama yang sudah set, kukus 5 menit.',
      'Lanjutkan bergantian hingga adonan habis. Lapisan terakhir kukus 10 menit.',
      'Dinginkan sempurna sebelum dipotong agar lapisan tidak rusak.',
    ],
  },
  {
    idMeal: 'id029',
    strMeal: 'Getuk Lindri Singkong',
    strCategory: 'Kue & Jajan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&q=80',
    cookTime: '40 menit',
    kalori: '170 kkal',
    porsi: '4 porsi',
    strIngredients: [
      { ing: 'Singkong', msr: '500 gram' },
      { ing: 'Gula pasir', msr: '100 gram' },
      { ing: 'Kelapa parut kukus', msr: '100 gram' },
      { ing: 'Garam', msr: '0,5 sdt' },
      { ing: 'Pasta pandan / pewarna', msr: 'secukupnya' },
      { ing: 'Santan', msr: '50 ml' },
    ],
    strInstructions: [
      'Kupas dan kukus singkong hingga benar-benar lunak dan matang.',
      'Haluskan singkong selagi panas, tambahkan gula, garam, dan santan. Uleni hingga rata.',
      'Bagi adonan, beri warna berbeda menggunakan pasta pandan, pewarna merah/kuning.',
      'Cetak adonan menggunakan cetakan getuk lindri atau pipihkan dan iris.',
      'Susun getuk berbagai warna di atas tampah. Sajikan dengan kelapa parut kukus.',
    ],
  },
  {
    idMeal: 'id030',
    strMeal: 'Wingko Babat Semarang',
    strCategory: 'Kue & Jajan',
    strArea: 'Indonesia',
    strMealThumb: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=400&q=80',
    cookTime: '35 menit',
    kalori: '280 kkal',
    porsi: '12 buah',
    strIngredients: [
      { ing: 'Kelapa parut kasar', msr: '300 gram' },
      { ing: 'Tepung ketan', msr: '200 gram' },
      { ing: 'Gula pasir', msr: '150 gram' },
      { ing: 'Santan kental', msr: '100 ml' },
      { ing: 'Telur', msr: '2 butir' },
      { ing: 'Garam', msr: '0,5 sdt' },
      { ing: 'Vanilla', msr: '0,5 sdt' },
    ],
    strInstructions: [
      'Campurkan kelapa parut, tepung ketan, gula, garam, dan vanilla. Aduk rata.',
      'Kocok telur, tambahkan santan, campurkan ke adonan kelapa. Aduk hingga rata.',
      'Panaskan teflon anti lengket, olesi sedikit margarin.',
      'Tuang adonan setebal 1 cm, tutup dan masak dengan api kecil.',
      'Masak hingga bagian bawah kecoklatan, balik hati-hati. Masak sisi lainnya.',
      'Angkat saat kedua sisi kecoklatan. Potong bundar atau biarkan bentuk asli.',
    ],
  },
];

export const getMealsByCategory = (category) => {
  if (!category || category === 'Semua') return MEALS_DB;
  return MEALS_DB.filter(m => m.strCategory === category);
};

export const getMealById = (id) => MEALS_DB.find(m => m.idMeal === id);

export const searchMeals = (query) => {
  if (!query || query.trim().length < 3) return [];
  const q = query.toLowerCase().trim();
  return MEALS_DB.filter(m =>
    m.strMeal.toLowerCase().includes(q) ||
    m.strCategory.toLowerCase().includes(q) ||
    m.strIngredients?.some(i => i.ing.toLowerCase().includes(q))
  );
};

export const getFeaturedMeals = () => MEALS_DB.filter(m => m.isFeatured);